# Generated by Django 5.0.6 on 2024-06-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_house_delete_item_delete_todolist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('loft', 'Loft'), ('studio', 'Studio')], max_length=100),
        ),
    ]
